import { deriveMetricTarget } from '#app/utils/intensity-target.ts'
import {
	type CardioDiscipline,
	type IntensityTarget,
} from '#app/utils/workout-schema.ts'
import {
	resolveIntensity,
	type DisciplineProfileForResolver,
	type ResolvedIntensity,
} from '#app/utils/zones/resolve.ts'
import { type ScheduledSession } from './schedule.ts'
import {
	type GeneratedBlock,
	type GeneratedStep,
	type PlanOutline,
} from './schema.ts'

/**
 * The transient Plan Preview returned to the wizard (PRD #103). Nothing here is
 * persisted; the preview is discarded by leaving the screen and regenerated by
 * re-running. It carries the Plan Outline plus the near-term dated sessions,
 * with each zone-label intensity resolved to concrete HR/power/pace ranges
 * against the athlete's recipe (ADR 0006) — left `unavailable` when no threshold
 * is configured, consistent with the existing fallback chain.
 */
export type PreviewStep =
	| (Extract<GeneratedStep, { kind: 'cardio' }> & {
			resolvedIntensity?: ResolvedIntensity
			/**
			 * The concrete metric Intensity Target to persist (#131): the generated
			 * zone label re-expressed as a pace / %FTP / HR target against the
			 * athlete's recipe, so the saved Step carries a real target the #130
			 * formatter renders — falling back to the zone label when no threshold
			 * resolves it. The preview still *displays* the zone label + resolved
			 * range; this is what the Step stores. Absent on steps without intensity.
			 */
			persistIntensity?: IntensityTarget
	  })
	| Extract<GeneratedStep, { kind: 'rest' }>

export type PreviewBlock = Omit<GeneratedBlock, 'steps'> & {
	steps: PreviewStep[]
}

export type PreviewSession = Omit<ScheduledSession, 'blocks'> & {
	blocks: PreviewBlock[]
}

export type PlanPreview = {
	outline: PlanOutline
	sessions: PreviewSession[]
}

export type ProfilesByDiscipline = Partial<
	Record<CardioDiscipline, DisciplineProfileForResolver | undefined>
>

/**
 * Outcome of resolving a generated plan's Intensity Target ranges (PRD #121,
 * #125). `resolved` means the resolution step ran — concrete ranges where a
 * threshold exists, honestly left blank where one does not (ADR 0006). `failed`
 * means the step itself errored, so the sessions persist without resolved
 * ranges; surfaced at the persistence seam rather than swallowed, so a failed
 * resolution never silently reads as a clean success.
 */
export type IntensityResolution = 'resolved' | 'failed'

/** Concrete cached range columns for a resolved (or absent) Intensity Target. */
export const EMPTY_INTENSITY_RANGE_COLUMNS = {
	intensityHrMin: null as number | null,
	intensityHrMax: null as number | null,
	intensityPowerMin: null as number | null,
	intensityPowerMax: null as number | null,
	intensityPaceMin: null as number | null,
	intensityPaceMax: null as number | null,
}

/**
 * Map a resolved Intensity Target onto the cached range columns persisted on a
 * Workout Step — the same mapping the authored-session post-write hook applies,
 * so a Generated Session's persisted ranges match its Plan Preview exactly. An
 * `unavailable` or absent resolution leaves every column null.
 */
export function intensityRangeColumns(
	resolved?: ResolvedIntensity,
): typeof EMPTY_INTENSITY_RANGE_COLUMNS {
	if (!resolved || resolved.unavailable) return EMPTY_INTENSITY_RANGE_COLUMNS
	return {
		intensityHrMin: resolved.hrMin ?? null,
		intensityHrMax: resolved.hrMax ?? null,
		intensityPowerMin: resolved.powerMin ?? null,
		intensityPowerMax: resolved.powerMax ?? null,
		intensityPaceMin: resolved.paceMin ?? null,
		intensityPaceMax: resolved.paceMax ?? null,
	}
}

export function buildPlanPreview(
	outline: PlanOutline,
	sessions: ScheduledSession[],
	profiles: ProfilesByDiscipline,
): PlanPreview {
	return {
		outline,
		sessions: sessions.map((session) => ({
			...session,
			blocks: session.blocks.map((block) => ({
				...block,
				steps: block.steps.map((step) => resolveStep(step, profiles)),
			})),
		})),
	}
}

function resolveStep(
	step: GeneratedStep,
	profiles: ProfilesByDiscipline,
): PreviewStep {
	if (step.kind !== 'cardio' || !step.intensity) return step

	const profile = profiles[step.discipline]
	if (!profile) {
		return {
			...step,
			resolvedIntensity: { unavailable: 'No profile configured' },
		}
	}
	return {
		...step,
		resolvedIntensity: resolveIntensity(step.intensity, profile),
		// Bake the per-discipline metric target to persist (#131); when no
		// threshold resolves it, this is the original zone label (Training Zone).
		persistIntensity: deriveMetricTarget(
			step.intensity,
			step.discipline,
			profile,
		),
	}
}
