import { type CardioDiscipline } from '#app/utils/workout-schema.ts'
import {
	resolveIntensity,
	type DisciplineProfileForResolver,
	type ResolvedIntensity,
} from '#app/utils/zones/resolve.ts'
import { type ScheduledSession } from './schedule.ts'
import {
	type GeneratedBlock,
	type GeneratedStep,
	type PlanOutline,
} from './schema.ts'

/**
 * The transient Plan Preview returned to the wizard (PRD #103). Nothing here is
 * persisted; the preview is discarded by leaving the screen and regenerated by
 * re-running. It carries the Plan Outline plus the near-term dated sessions,
 * with each zone-label intensity resolved to concrete HR/power/pace ranges
 * against the athlete's recipe (ADR 0006) — left `unavailable` when no threshold
 * is configured, consistent with the existing fallback chain.
 */
export type PreviewStep =
	| (Extract<GeneratedStep, { kind: 'cardio' }> & {
			resolvedIntensity?: ResolvedIntensity
	  })
	| Extract<GeneratedStep, { kind: 'rest' }>

export type PreviewBlock = Omit<GeneratedBlock, 'steps'> & { steps: PreviewStep[] }

export type PreviewSession = Omit<ScheduledSession, 'blocks'> & {
	blocks: PreviewBlock[]
}

export type PlanPreview = {
	outline: PlanOutline
	sessions: PreviewSession[]
}

export type ProfilesByDiscipline = Partial<
	Record<CardioDiscipline, DisciplineProfileForResolver | undefined>
>

export function buildPlanPreview(
	outline: PlanOutline,
	sessions: ScheduledSession[],
	profiles: ProfilesByDiscipline,
): PlanPreview {
	return {
		outline,
		sessions: sessions.map((session) => ({
			...session,
			blocks: session.blocks.map((block) => ({
				...block,
				steps: block.steps.map((step) => resolveStep(step, profiles)),
			})),
		})),
	}
}

function resolveStep(step: GeneratedStep, profiles: ProfilesByDiscipline): PreviewStep {
	if (step.kind !== 'cardio' || !step.intensity) return step

	const profile = profiles[step.discipline]
	if (!profile) {
		return { ...step, resolvedIntensity: { unavailable: 'No profile configured' } }
	}
	return { ...step, resolvedIntensity: resolveIntensity(step.intensity, profile) }
}
